CREATE TABLE [ref].[Units]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FactionId] INT NOT NULL,
	[Label] NVARCHAR(75) NOT NULL,
	[Quantity] TINYINT NOT NULL DEFAULT 1,
	[Quality] TINYINT NOT NULL DEFAULT 3,
	[Defense] TINYINT NOT NULL DEFAULT 3,
	[Cost] SMALLINT NOT NULL DEFAULT 0,
	CONSTRAINT FK_Units_FactionId FOREIGN KEY ([FactionId]) REFERENCES [ref].[Factions]([Id])
)
