CREATE PROCEDURE ref.[sp_datatable_equipment_alienhives]
AS
begin
	declare @datatable table (label nvarchar(75))

	insert into @datatable
		(label)
	values
		('Razor Claws')
		,('Stomp')
		,('Heavy Piercing Claws')
		,('Bio-Borers')
		,('Piercing Claws')
		,('Swarm Attacks')
		,('Psy-Blasts')
		,('Psy-Shocks')
		,('Whip LImgs')
		,('Serrated Claws')
		,('Piercing Claws')
		,('Razor Whip')
		,('Sword Claws')
		,('Smashing Claws')
		,('Spitter Cannon')
		,('Shredder Cannon')
		,('Heavy Ravager Cannon')
		,('Barb Cannon')
		,('Acid Cannon')
		,('Hive Conduit')
		,('Bio-Recovery')
		,('Hive Protector')
		,('Brood Leader')
		,('Spitter Gun')
		,('Twin Spine Guns')
		,('Wings')
		,('Serrated Claws')
		,('Heavy Bite')
		,('Adrenaline')
		,('Toxic Cysts')
		,('Bio-Spiner')
		,('Bio-Ravager')
		,('Bio-Flamer')
		,('Bio-Fuser')
		,('Bio-Plasma')
		,('Bio-Shredder')
		,('Bio-Spiker')
		,('Mind Snatcher')
		,('Shock Harpoon')
		,('Acid Launcher')
		,('Barb Gun')
		,('Skewer Cannon')
		,('Burrow Attack')
		,('Rapid Strike')
		,('Tunnel Attack')
		,('Takedown')
		,('Vicious Jaws')
		,('Acid Spurt')
		,('Heavy Psy-Blast')
		,('Tongue')
		,('Toxic Spray')
		,('Rapid Stinger Cannon')
		,('Shredder Bio-Artillery')
		,('Spit Flames')
		,('Spore Gun')
		,('Razor Tendrils')
		,('Stinger Spitter')
		,('Caustic Cannon')
		,('Spore Bombs')
		,('Titanic Jaws')
		,('Titanic Stomp')
		,('Battering Tusks')
		,('Bio-Pods')
		,('Fracture Cannon')
		,('Spitter Bio-Artillery')
		,('Acid Bio-Artillery')
		,('Plasma Bio-Artillery')
		,('Spitter Gun Array')
		,('Shredder Gun Array')
		,('Barb Cannon Array')
		,('Acid Cannon Array')
		,('Twin Barb Cannon')
		,('Twin Acid Cannon')
		,('Missle Bugs')
		,('Toxic Breath')
		,('Explosive Spit')
		,('Acid Blood')
		,('Hive Carrier')

	select
		* 
	from
		@datatable
	group by 
		label
	order by label
end