CREATE PROCEDURE ref.[sp_datatable_unitspecialrules_battlebrothers]
as
begin
	declare @result table (unit nvarchar(75), specialrule nvarchar(75), value tinyint)

	insert into @result
		(unit, specialrule, value)
	values
		('Master Brother', 'Fearless', 0)
		,('Master Brother', 'Hero', 0)
		,('Master Brother', 'Tough', 3)
		,('Elite Pathfinder', 'Fearless', 0)
		,('Elite Pathfinder', 'Hero', 0)
		,('Elite Pathfinder', 'Strider', 0)
		,('Elite Pathfinder', 'Tough', 3)
		,('Pathfinders', 'Fearless', 0)
		,('Pathfinders', 'Strider', 0)
		,('Assault Brothers', 'Fearless', 0)
		,('Battle Brothers', 'Fearless', 0)
		,('Support Brothers', 'Fearless', 0)
		,('Support Brothers', 'Relentless', 0)
		,('Destroyers', 'Ambush', 0)
		,('Destroyers', 'Fearless', 0)
		,('Destroyers', 'Tough', 3)
		,('Pathfinder Bikers', 'Fast', 0)
		,('Pathfinder Bikers', 'Fearless', 0)
		,('Pathfinder Bikers', 'Scout', 0)
		,('Pathfinder Bikers', 'Tough', 3)
		,('Brother Bikers', 'Fast', 0)
		,('Brother Bikers', 'Fearless', 0)
		,('Brother Bikers', 'Tough', 3)
		,('Support Bike', 'Fast', 0)
		,('Support Bike', 'Fearless', 0)
		,('Support Bike', 'Tough', 6)
		,('APC', 'Fast', 0)
		,('APC', 'Fearless', 0)
		,('APC', 'Impact', 6)
		,('APC', 'Tough', 6)
		,('APC', 'Transport', 11)
		,('Attack APC', 'Fast', 0)
		,('Attack APC', 'Fearless', 0)
		,('Attack APC', 'Impact', 6)
		,('Attack APC', 'Tough', 6)
		,('Attack APC', 'Transport', 11)
		,('Drop Pod', 'Ambush', 0)
		,('Drop Pod', 'Fearless', 0)
		,('Drop Pod', 'Immobile', 0)
		,('Drop Pod', 'Tough', 6)
		,('Drop Pod', 'Transport', 11)
		,('Battle Tank', 'Fast', 0)
		,('Battle Tank', 'Fearless', 0)
		,('Battle Tank', 'Impact', 6)
		,('Battle Tank', 'Tough', 12)
		,('Heavy Tank', 'Fast', 0)
		,('Heavy Tank', 'Fearless', 0)
		,('Heavy Tank', 'Impact', 6)
		,('Heavy Tank', 'Tough', 18)
		,('Heavy Tank', 'Transport', 11)
		,('Artillery Gun', 'Fearless', 0)
		,('Artillery Gun', 'Repair', 0)
		,('Artillery Gun', 'Slow', 0)
		,('Artillery Gun', 'Tough', 6)
		,('Attack Speeder', 'Ambush', 0)
		,('Attack Speeder', 'Fast', 0)
		,('Attack Speeder', 'Fearless', 0)
		,('Attack Speeder', 'Impact', 6)
		,('Attack Speeder', 'Strider', 0)
		,('Attack Speeder', 'Tough', 6)
		,('Heavy Exo-Suit', 'Fast', 0)
		,('Heavy Exo-Suit', 'Fearless', 0)
		,('Heavy Exo-Suit', 'Tough', 6)
		,('Attack Walker', 'Fast', 0)
		,('Attack Walker', 'Fearless', 0)
		,('Attack Walker', 'Tough', 12)
		,('Light Gunship', 'Aircraft', 0)
		,('Light Gunship', 'Fearless', 0)
		,('Light Gunship', 'Tough', 6)
		,('Heavy Gunship', 'Aircraft', 0)
		,('Heavy Gunship', 'Fearless', 0)
		,('Heavy Gunship', 'Tough', 9)
		,('Heavy Gunship', 'Transport', 11)		

	select
		(select u.id from ref.units u inner join ref.Factions f on u.FactionId = f.Id inner join ref.Games g on f.GameId = g.Id where g.Short = 'GF' and u.Label = unit) as unitid,
		(select s.id from ref.SpecialRules s where s.Label = specialrule) as specialruleid,
		r.value
	from
		@result r
end