CREATE PROCEDURE ref.[sp_datatable_unitspecialrules_alienhives]
as
begin
	declare @result table (unit nvarchar(75), specialrule nvarchar(75), value tinyint)

	insert into @result
		(unit, specialrule, value)
	values
		('Hive Lord', 'Fear', 0)
		,('Hive Lord', 'Fearless', 0)
		,('Hive Lord', 'Hero', 0)
		,('Hive Lord', 'Tough', 12)
		,('Snatcher Lord', 'Fast', 0)
		,('Snatcher Lord', 'Hero', 0)
		,('Snatcher Lord', 'Psychic', 1)
		,('Snatcher Lord', 'Scout', 0)
		,('Snatcher Lord', 'Strider', 0)
		,('Snatcher Lord', 'Tough', 3)
		,('Prime Warrior', 'Fearless', 0)
		,('Prime Warrior', 'Hero', 0)
		,('Prime Warrior', 'Tough', 6)
		,('Assault Grunts', 'Fast', 0)
		,('Assault Grunts', 'Strider', 0)
		,('Shooter Grunts', 'Strider', 0)
		,('Winged Grunts', 'Ambush', 0)
		,('Winged Grunts', 'Flying', 0)
		,('Soul-Snatchers', 'Fast', 0)
		,('Soul-Snatchers', 'Scout', 0)
		,('Soul-Snatchers', 'Strider', 0)
		,('Hive Warriors', 'Fearless', 0)
		,('Hive Warriors', 'Tough', 3)
		,('Hive Guardians', 'Relentless', 0)
		,('Hive Guardians', 'Tough', 3)
		,('Hive Swarm', 'Fearless', 0)
		,('Hive Swarm', 'Strider', 0)
		,('Hive Swarm', 'Tough', 3)
		,('Ravenous Beasts', 'Fast', 0)
		,('Ravenous Beasts', 'Strider', 0)
		,('Ravenous Beasts', 'Tough', 3)
		,('Synapse Floaters', 'Psychic Synapse', 0)
		,('Synapse Floaters', 'Stealth', 0)
		,('Synapse Floaters', 'Tough', 3)
		,('Venom Floaters', 'Shrouding Mist', 0)
		,('Venom Floaters', 'Stealth', 0)
		,('Venom Floaters', 'Tough', 3)
		,('Shadow Hunter', 'Ambush', 0)
		,('Shadow Hunter', 'Fast', 0)
		,('Shadow Hunter', 'Fear', 0)
		,('Shadow Hunter', 'Stealth', 0)
		,('Shadow Hunter', 'Strider', 0)
		,('Shadow Hunter', 'Tough', 6)
		,('Carnivo-Rex', 'Fear', 0)
		,('Carnivo-Rex', 'Fearless', 0)
		,('Carnivo-Rex', 'Tough', 12)
		,('Toxico-Rex', 'Fear', 0)
		,('Toxico-Rex', 'Fearless', 0)
		,('Toxico-Rex', 'Shrouding Mist', 0)
		,('Toxico-Rex', 'Stealth', 0)
		,('Toxico-Rex', 'Tough', 12)
		,('Psycho-Rex', 'Fear', 0)
		,('Psycho-Rex', 'Fearless', 0)
		,('Psycho-Rex', 'Psychic', 2)
		,('Psycho-Rex', 'Stealth', 0)
		,('Psycho-Rex', 'Tough', 12)
		,('Devourer Beast', 'Fear', 0)
		,('Devourer Beast', 'Tough', 18)
		,('Tyrant Beast', 'Fear', 0)
		,('Tyrant Beast', 'Tough', 18)
		,('Spawning Beast', 'Fear', 0)
		,('Spawning Beast', 'Spawn Brood', 0)
		,('Spawning Beast', 'Tough', 18)
		,('Artillery Beast', 'Fear', 0)
		,('Artillery Beast', 'Tough', 18)
		,('Burrower', 'Fear', 0)
		,('Burrower', 'Surprise Attack', 0)
		,('Burrower', 'Tough', 18)
		,('Flamer Beast', 'Fear', 0)
		,('Flamer Beast', 'Fearless', 0)
		,('Flamer Beast', 'Tough', 6)
		,('Mortar Beast', 'Fear', 0)
		,('Mortar Beast', 'Fearless', 0)
		,('Mortar Beast', 'Tough', 6)
		,('Invasion Carrier', 'Ambush', 0)
		,('Invasion Carrier', 'Fear', 0)
		,('Invasion Carrier', 'Fearless', 0)
		,('Invasion Carrier', 'Tough', 6)
		,('Invasion Carrier', 'Transport', 11)
		,('Invasion Artillery', 'Ambush', 0)
		,('Invasion Artillery', 'Fear', 0)
		,('Invasion Artillery', 'Fearless', 0)
		,('Invasion Artillery', 'Slow', 0)
		,('Invasion Artillery', 'Tough', 6)
		,('Hive Titan', 'Fear', 0)
		,('Hive Titan', 'Regeneration', 0)
		,('Hive Titan', 'Tough', 24)
		,('Spores', 'Explode', 1)
		,('Massive Spore', 'Explode', 3)
		,('Massive Spore', 'Tough', 3)
		,('Rapacious Beast', 'Aircraft', 0)
		,('Rapacious Beast', 'Fearless', 0)
		,('Rapacious Beast', 'Tough', 6)

	select
		(select u.id from ref.units u inner join ref.Factions f on u.FactionId = f.Id inner join ref.Games g on f.GameId = g.Id where g.Short = 'GF' and u.Label = unit) as unitid,
		(select s.id from ref.SpecialRules s where s.Label = specialrule) as specialruleid,
		r.value
	from
		@result r
end