CREATE PROCEDURE ref.[sp_datatable_equipment_battlebrothers]
	AS
begin
	declare @datatable table (label nvarchar(75))

	insert into @datatable
		(label)
	values
		('Heavy Rifle')
		,('CCW')
		,('CCWs')
		,('Heavy Rifles')
		,('Heavy Pistol')
		,('Heavy Pistols')
		,('Heavy Flamethrowers')
		,('Dual Energy Claws')
		,('Greande Launchers')
		,('Twin Heavy Rifle')
		,('Twin Heavy Rifles')
		,('Heavy Chainsaw Sword')
		,('Combat Shield')
		,('Plasma Pistol')
		,('Gravity Pistol')
		,('Storm Rifle')
		,('Energy Hammer')
		,('Energy Sword')
		,('Chain-Fist')
		,('Energy Fist')
		,('Plasma Mod')
		,('Fusion-Mod')
		,('Flamer-Mod')
		,('Gravity-Mod')
		,('Jetpack')
		,('Destroyer Armor')
		,('Combat Bike')
		,('Veteran Infantry')
		,('Preacher')
		,('Archivist')
		,('Engineer')
		,('Captain')
		,('Camo Cloak')
		,('Forward Sentry')
		,('Shotgun')
		,('Plasma Rifle')
		,('Flamethrower')
		,('Gravity Rifle')
		,('Heavy Machinegun')
		,('Missle Launcher')
		,('Camo Cloaks')
		,('Forward Sentries')
		,('Jetpacks')
		,('Battle Standard')
		,('Medical Training')
		,('Laser Cannon')
		,('Cyclone Missles')
		,('Fusion Rifle')
		,('Heavy Fusion Rifle')
		,('Heavy Machinegun')
		,('Twin Heavy Flamethrower')
		,('Death Launcher')
		,('Twin Heavy Machineguns')
		,('Demolition CAnnon')
		,('Engineer Crew')
		,('Heavy Flak Cannon')
		,('Twin Fusion Rifle')
		,('Stomp')
		,('Walker Fists')
		,('Twin Typhoon Missles')
		,('Miniguns')
		,('Storm Missles')
		,('Twin Minigun')
		,('Typhoon Missles')
		,('Dozer Blade')
		,('Hunter Missles')
		,('Laser Cannon')
		,('Twin Laser Cannon')
		,('Twin Plasma Rifle')
		,('Spear Missle Launcher')
		,('Rapid Autocannon')
		,('Twin Storm Cannon')
		,('Quad Laser Cannons')
		,('Twin Heavy Rifle Arrays')
		,('Heavy Fusion Rifle')
		,('Heavy Gatling Cannon')
		,('Heavy Thunder Cannon')
		,('Heavy Crack Cannon')
		,('Dual Heavy Fists')
		,('Heavy Rifle Array')
		,('Cyclone Missle Array')
		,('Twin Gravity Cannon')
		,('Dual Combat Drills')
		,('Cyclone Missles Array')
		,('Missle Array')
		,('Heavy Plasma Cannon')
		,('Veteran Walker')
		,('Laser Talon')
		,('Storm Cannon')
		,('Boosted Fusion Rifles')
		,('Heavy Rifle Arrays')
	
	SELECT * from @datatable
end